Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'AddAnyConstituentAttributeWStartDateATTRIBUTECATEGORIES' data form
''' </summary>
Partial Public Class [AddAnyConstituentAttributeWStartDateATTRIBUTECATEGORIESUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.UIModel

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _id As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _datatypecode As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _constituentsearchlistcatalogid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _codetablename As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _id = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _datatypecode = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _constituentsearchlistcatalogid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _codetablename = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        '
        '_id
        '
        _id.Name = "ID"
        _id.Caption = "ID"
        Me.Fields.Add(_id)
        '
        '_datatypecode
        '
        _datatypecode.Name = "DATATYPECODE"
        _datatypecode.Caption = "DATATYPECODE"
        Me.Fields.Add(_datatypecode)
        '
        '_constituentsearchlistcatalogid
        '
        _constituentsearchlistcatalogid.Name = "CONSTITUENTSEARCHLISTCATALOGID"
        _constituentsearchlistcatalogid.Caption = "CONSTITUENTSEARCHLISTCATALOGID"
        Me.Fields.Add(_constituentsearchlistcatalogid)
        '
        '_codetablename
        '
        _codetablename.Name = "CODETABLENAME"
        _codetablename.Caption = "CODETABLENAME"
        Me.Fields.Add(_codetablename)

		OnCreated()

    End Sub
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _id
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DATATYPECODE]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _datatypecode
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CONSTITUENTSEARCHLISTCATALOGID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _constituentsearchlistcatalogid
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CODETABLENAME]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _codetablename
        End Get
    End Property
    
End Class
