Option Strict On
Option Explicit On
Option Infer On

'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by BBUIModelLibrary
'     Version:  2.93.2034.0
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
''' <summary>
''' Represents the UI model for the 'Add any constituent attribute w/ start date' data form
''' </summary>

Partial Public Class [AddAnyConstituentAttributeWStartDateUIModel]
	Inherits Global.Blackbaud.AppFx.UIModeling.Core.CustomUIModel

#Region "Enums"

    ''' <summary>
    ''' Enumerated values for use with the BOOLEANVALUE property
    ''' </summary>
	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Enum BOOLEANVALUES As Integer
        [No] = 0
        [Yes] = 1
    End Enum

#End Region

#Region "Extensibility methods"

    Partial Private Sub OnCreated()
    End Sub

#End Region

    Private WithEvents _idsetregisterid As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _recordtypeid As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
    Private WithEvents _attributecategoryid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _stringvalue As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _numbervalue As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
    Private WithEvents _moneyvalue As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
    Private WithEvents _datevalue As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _booleanvalue As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of BOOLEANVALUES))
    Private WithEvents _codetablevalue As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
    Private WithEvents _fuzzydatevalue As Global.Blackbaud.AppFx.UIModeling.Core.FuzzyDateField
    Private WithEvents _constituentidvalue As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
    Private WithEvents _hourminutevalue As Global.Blackbaud.AppFx.UIModeling.Core.HourMinuteField
    Private WithEvents _memovalue As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _attributecategories As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of AddAnyConstituentAttributeWStartDateATTRIBUTECATEGORIESUIModel)
    Private WithEvents _startdate As Global.Blackbaud.AppFx.UIModeling.Core.DateField
    Private WithEvents _comment As Global.Blackbaud.AppFx.UIModeling.Core.StringField
    Private WithEvents _removeunqualified As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _overwriteexistingvalue As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
    Private WithEvents _currencyid As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
    Private WithEvents _uivaluefield As Global.Blackbaud.AppFx.UIModeling.Core.StringField

	<System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public Sub New()
        MyBase.New()

        _idsetregisterid = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _recordtypeid = New Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        _attributecategoryid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _stringvalue = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _numbervalue = New Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        _moneyvalue = New Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        _datevalue = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _booleanvalue = New Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of BOOLEANVALUES))
        _codetablevalue = New Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        _fuzzydatevalue = New Global.Blackbaud.AppFx.UIModeling.Core.FuzzyDateField
        _constituentidvalue = New Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        _hourminutevalue = New Global.Blackbaud.AppFx.UIModeling.Core.HourMinuteField
        _memovalue = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _attributecategories = New Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of AddAnyConstituentAttributeWStartDateATTRIBUTECATEGORIESUIModel)
        _startdate = New Global.Blackbaud.AppFx.UIModeling.Core.DateField
        _comment = New Global.Blackbaud.AppFx.UIModeling.Core.StringField
        _removeunqualified = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _overwriteexistingvalue = New Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        _currencyid = New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        _uivaluefield = New Global.Blackbaud.AppFx.UIModeling.Core.StringField

        '
        '_idsetregisterid
        '
        _idsetregisterid.Name = "IDSETREGISTERID"
        _idsetregisterid.Caption = "Selection"
        _idsetregisterid.SearchListID = New Guid("98d0070e-c4a7-495b-a438-2ac12da79068")
        _idsetregisterid.EnableQuickFind = True
        _idsetregisterid.SearchFieldOverrides.Add(New Global.Blackbaud.AppFx.UIModeling.Core.FieldOverride() With {.FieldId = "RECORDTYPEID", .Caption = "Record type", .ReadOnly = True, .DefaultValueText = "Fields!RECORDTYPEID"})
        _idsetregisterid.SystemSearchType = Global.Blackbaud.AppFx.UIModeling.Core.SystemSearchType.Selection
        Me.Fields.Add(_idsetregisterid)
        '
        '_recordtypeid
        '
        _recordtypeid.Name = "RECORDTYPEID"
        _recordtypeid.Caption = "RECORDTYPEID"
        _recordtypeid.Visible = False
        _recordtypeid.DBReadOnly = True
        Me.Fields.Add(_recordtypeid)
        '
        '_attributecategoryid
        '
        _attributecategoryid.Name = "ATTRIBUTECATEGORYID"
        _attributecategoryid.Caption = "Category"
        _attributecategoryid.Required = True
        _attributecategoryid.SimpleDataListID = New Guid("958132a3-762a-4844-b7a1-f3a3098da95a")
        _attributecategoryid.Parameters.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListParameter("RECORDTYPE", "Constituent"))
        Me.Fields.Add(_attributecategoryid)
        '
        '_stringvalue
        '
        _stringvalue.Name = "STRINGVALUE"
        _stringvalue.Caption = "Value"
        _stringvalue.MaxLength = 250
        Me.Fields.Add(_stringvalue)
        '
        '_numbervalue
        '
        _numbervalue.Name = "NUMBERVALUE"
        _numbervalue.Caption = "Value"
        Me.Fields.Add(_numbervalue)
        '
        '_moneyvalue
        '
        _moneyvalue.Name = "MONEYVALUE"
        _moneyvalue.Caption = "Value"
        _moneyvalue.CurrencyFieldId = "CURRENCYID"
        Me.Fields.Add(_moneyvalue)
        '
        '_datevalue
        '
        _datevalue.Name = "DATEVALUE"
        _datevalue.Caption = "Value"
        Me.Fields.Add(_datevalue)
        '
        '_booleanvalue
        '
        _booleanvalue.Name = "BOOLEANVALUE"
        _booleanvalue.Caption = "Value"
        _booleanvalue.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of BOOLEANVALUES)) With {.Value = BOOLEANVALUES.[No], .Translation = "No"})
        _booleanvalue.DataSource.Add(New Global.Blackbaud.AppFx.UIModeling.Core.ValueListItem(Of Nullable(Of BOOLEANVALUES)) With {.Value = BOOLEANVALUES.[Yes], .Translation = "Yes"})
        Me.Fields.Add(_booleanvalue)
        '
        '_codetablevalue
        '
        _codetablevalue.Name = "CODETABLEVALUE"
        _codetablevalue.Caption = "Value"
        _codetablevalue.CodeTableName = "ADDRESSTYPECODE"
        Me.Fields.Add(_codetablevalue)
        '
        '_fuzzydatevalue
        '
        _fuzzydatevalue.Name = "FUZZYDATEVALUE"
        _fuzzydatevalue.Caption = "Value"
        Me.Fields.Add(_fuzzydatevalue)
        '
        '_constituentidvalue
        '
        _constituentidvalue.Name = "CONSTITUENTIDVALUE"
        _constituentidvalue.Caption = "Value"
        _constituentidvalue.SearchListID = New Guid("23c5c603-d7d8-4106-aecc-65392b563887")
        _constituentidvalue.EnableQuickFind = True
        _constituentidvalue.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("1986f0cf-efb6-48b3-afde-950b57562434"), "Individual"))
        _constituentidvalue.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("d846a816-46c7-470e-9ad0-973b2730e836"), "Household"))
        _constituentidvalue.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("f0f6426a-fccd-48bb-846b-eb3d1a4a0ed4"), "Group"))
        _constituentidvalue.SearchListAddForms.Add(New Global.Blackbaud.AppFx.UIModeling.Core.SearchListAddForm(New Guid("ca3ed110-a5f0-4b5b-8eb7-0616e0a82e8e"), "Organization"))
        Me.Fields.Add(_constituentidvalue)
        '
        '_hourminutevalue
        '
        _hourminutevalue.Name = "HOURMINUTEVALUE"
        _hourminutevalue.Caption = "Value"
        Me.Fields.Add(_hourminutevalue)
        '
        '_memovalue
        '
        _memovalue.Name = "MEMOVALUE"
        _memovalue.Caption = "Value"
        Me.Fields.Add(_memovalue)
        '
        '_attributecategories
        '
        _attributecategories.Name = "ATTRIBUTECATEGORIES"
        _attributecategories.Caption = "ATTRIBUTECATEGORIES"
        _attributecategories.DBReadOnly = True
        _attributecategories.AvailableToClient = False
        Me.Fields.Add(_attributecategories)
        '
        '_startdate
        '
        _startdate.Name = "STARTDATE"
        _startdate.Caption = "Start Date"
        Me.Fields.Add(_startdate)
        '
        '_comment
        '
        _comment.Name = "COMMENT"
        _comment.Caption = "Comment"
        _comment.MaxLength = 255
        Me.Fields.Add(_comment)
        '
        '_removeunqualified
        '
        _removeunqualified.Name = "REMOVEUNQUALIFIED"
        _removeunqualified.Caption = "Remove value from unqualified records"
        Me.Fields.Add(_removeunqualified)
        '
        '_overwriteexistingvalue
        '
        _overwriteexistingvalue.Name = "OVERWRITEEXISTINGVALUE"
        _overwriteexistingvalue.Caption = "Overwrite existing value"
        _overwriteexistingvalue.Value = True
        Me.Fields.Add(_overwriteexistingvalue)
        '
        '_currencyid
        '
        _currencyid.Name = "CURRENCYID"
        _currencyid.Caption = "Currency"
        _currencyid.SimpleDataListID = New Guid("13612288-b37e-409d-ba52-6ab31637ddd6")
        Me.Fields.Add(_currencyid)
        '
        '_uivaluefield
        '
        _uivaluefield.Name = "UIVALUEFIELD"
        _uivaluefield.Caption = "Value"
        _uivaluefield.Visible = False
        _uivaluefield.DBReadOnly = True
        _uivaluefield.AvailableToClient = False
        Me.Fields.Add(_uivaluefield)

		OnCreated()

    End Sub
    
    ''' <summary>
    ''' Selection
    ''' </summary>
    <System.ComponentModel.Description("Selection")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [IDSETREGISTERID]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _idsetregisterid
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [RECORDTYPEID]() As Global.Blackbaud.AppFx.UIModeling.Core.GuidField
        Get
            Return _recordtypeid
        End Get
    End Property
    
    ''' <summary>
    ''' Category
    ''' </summary>
    <System.ComponentModel.Description("Category")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ATTRIBUTECATEGORYID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _attributecategoryid
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [STRINGVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _stringvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [NUMBERVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.IntegerField
        Get
            Return _numbervalue
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MONEYVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.MoneyField
        Get
            Return _moneyvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [DATEVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _datevalue
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [BOOLEANVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.ValueListField(Of Nullable(Of BOOLEANVALUES))
        Get
            Return _booleanvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CODETABLEVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.CodeTableField
        Get
            Return _codetablevalue
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [FUZZYDATEVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.FuzzyDateField
        Get
            Return _fuzzydatevalue
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CONSTITUENTIDVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.SearchListField(Of Guid)
        Get
            Return _constituentidvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [HOURMINUTEVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.HourMinuteField
        Get
            Return _hourminutevalue
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [MEMOVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _memovalue
        End Get
    End Property
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [ATTRIBUTECATEGORIES]() As Global.Blackbaud.AppFx.UIModeling.Core.CollectionField(Of AddAnyConstituentAttributeWStartDateATTRIBUTECATEGORIESUIModel)
        Get
            Return _attributecategories
        End Get
    End Property
    
    ''' <summary>
    ''' Start Date
    ''' </summary>
    <System.ComponentModel.Description("Start Date")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [STARTDATE]() As Global.Blackbaud.AppFx.UIModeling.Core.DateField
        Get
            Return _startdate
        End Get
    End Property
    
    ''' <summary>
    ''' Comment
    ''' </summary>
    <System.ComponentModel.Description("Comment")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [COMMENT]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _comment
        End Get
    End Property
    
    ''' <summary>
    ''' Remove value from unqualified records
    ''' </summary>
    <System.ComponentModel.Description("Remove value from unqualified records")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [REMOVEUNQUALIFIED]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _removeunqualified
        End Get
    End Property
    
    ''' <summary>
    ''' Overwrite existing value
    ''' </summary>
    <System.ComponentModel.Description("Overwrite existing value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [OVERWRITEEXISTINGVALUE]() As Global.Blackbaud.AppFx.UIModeling.Core.BooleanField
        Get
            Return _overwriteexistingvalue
        End Get
    End Property
    
    ''' <summary>
    ''' Currency
    ''' </summary>
    <System.ComponentModel.Description("Currency")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [CURRENCYID]() As Global.Blackbaud.AppFx.UIModeling.Core.SimpleDataListField(Of Guid)
        Get
            Return _currencyid
        End Get
    End Property
    
    ''' <summary>
    ''' Value
    ''' </summary>
    <System.ComponentModel.Description("Value")> _
    <System.CodeDom.Compiler.GeneratedCodeAttribute("BBUIModelLibrary", "2.93.2034.0")> _
    Public ReadOnly Property [UIVALUEFIELD]() As Global.Blackbaud.AppFx.UIModeling.Core.StringField
        Get
            Return _uivaluefield
        End Get
    End Property
    
End Class
